<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <link rel="stylesheet" href="admin_student_addnew.css">
</head>
<body>
    <?php
        include("admin_navigator.php");
        include("conn.php");
    ?>

    <form action="admin_student_insert.php" method="POST" enctype="multipart/form-data">
    <div class="profile">

        <div id="profileimage"><input type="file" name="student_profilepic" id="img" style="display:none;"/>
                <label for="img" id="changeimg">Click me to upload image</label>
        </div>

        <span class="myid"> Student ID: Autogenerate </span>
        <span class="mydate"> Date Registered: Autogenerate</span>

        <div id="informationbackground">
            <hr id="divider">
            <span id="first">First Name:<br><br>
                <input type="text" placeholder="First Name" class="inputbox" name="student_firstname" required pattern="[^\d]+" title="Digits are not allowed!">
            </span>

            <span id="last">Last Name: <br><br>
                <input type="text" placeholder="Last Name" class="inputbox" name="student_lastname" required pattern="[^\d]+" title="Digits are not allowed!">
            </span>

            <span id="gender">Gender: <br><br>
                <select class="inputbox2" name="student_gender" required>
                    <option value="none">none</option>
                    <option value="male">male</option>
                    <option value="female">female</option>
                </select>
            </span>

            <span id="ic">IC Number: <br><br>
                <input type="text" placeholder="IC Number" class="inputbox" name="student_ic" required pattern="[0-9]+" title="Only Integers are Accepted!">
            </span>

            <span id="bday">Birth Date:<br><br>
                <input type="date" placeholder="Birthday" class="inputbox" name="student_birthdate" required>
            </span>

            <span id="mobilenum">Mobile Number: <br><br>
                <input type="tel" placeholder="Mobile Number" class="inputbox" name="student_mobilenum" required pattern="[0-9]+" title="Only Integers are Accepted!">
            </span>

            <span id="address">Address: <br><br>
                <textarea placeholder="Address:" class="textarea" name="student_address" required></textarea>
            </span>

            <span id="country">Country: <br><br>
                <select class="inputbox2" name="student_country" required>
                    <option value="None" >None</option>
                    <option value="Malaysia">Malaysia</option>
                    <option value="Other">Other</option>
                </select>
            </span>
        </div>

        <button id="profilesave">Save Changes</button>

        <div id="credentialbutton" onclick=credentials()>Login Credential</div>

        <div id="logincredentials">

            <span id="loginemail">Email: <br><br>
                <input type="email" placeholder="Email Address" class="inputbox3" name="student_email" required>
            </span>

            <span id="loginpassword">Password: <br><br>
                <input type="password" placeholder="Password" name="student_password" minlength="6" title="Minimum 6 characters or digits!" class="inputbox3" id="passwordview" required><i class='bx bx-show' id="showpassword" onclick=password()></i>
            </span>

        </div> 
    </div>

    <div class="studside">
        <span id="studtitle">Supervised By: </span>
        <div id="superpic"></div>

        <span class="superid">Supervisor ID: Autogenerated</span>
        <br>

        <span class="super1">Supervisor Name: <br><br>
        <select placeholder="supername" id="supername" name="student_supervisor" required>
            <option value="none"> none </option>
            <?php
                $supervisor = mysqli_query($con,"SELECT * FROM supervisor");
                while ($row = mysqli_fetch_array($supervisor)){
                    echo '<option value="'.$row["supervisor_firstname"].' '.$row["supervisor_lastname"].'">'.$row["supervisor_firstname"].' '.$row["supervisor_lastname"].'</option>'; 
                }
            ?>
        </select>
        </span>
        <br>
        <span class="progid">Program ID: Autogenerated</span>
        <br>
        <span class="super1">Program Name: <br><br>
        <select placeholder="progname" id="progname" name="student_program" required>
            <option value="none"> none </option>
            <?php
                $program = mysqli_query($con,"SELECT * FROM program");
                while ($row = mysqli_fetch_array($program)){
                    echo '<option value="'.$row["program_name"].'">'.$row["program_name"].'</option>'; 
                }
            ?>
        </select>
        </span>
    </div>
    </form>


    <script>
        let title = document.getElementById("title");
        title.innerHTML="Student Registration";

        var login = true;
        function credentials(){
            let loginboard = document.getElementById("logincredentials");
            loginboard.style.display = login ? "block" + $("#logincredentials").slideDown() : "none" + $("#logincredentials").slideUp(); 
            login = !login; 
        }

        function password(){
            let passwordField = document.getElementById("passwordview");

            if(passwordField.type == 'password') {
                passwordField.type = 'text';
            }
            else {
                passwordField.type = 'password';
            }
        } 

        document.getElementById("nav_student").className = "active"; 
    </script>
</body>
</html>