<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Grading Report</title>
    <link rel="stylesheet" href="grade_report.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>
    <a href="admin_report.php" ><div id="goback"><i class='bx bx-chevrons-left' id="icon"></i>Back</div></a>
    <span id="progtitle">Please Provide a Program Name: </span>

    <form action="grade_report.php" method="GET">
        <select required id="programselection" name="program">
            <option value="none">none</option>
            <?php
                include("conn.php");
                include("session.php");

                $result = mysqli_query($con, "SELECT * FROM program");
                while ($row = mysqli_fetch_array($result)){
                    echo '<option value="'.$row["program_name"].'">'.$row["program_name"].'</option>';
                }

            ?>
        </select>
        <button type="submit" class="submitbutton">Submit</button>
    </form>


    <div id="print" onclick="window.print()"><i class='bx bx-printer'></i></div>

    <?php
        $programID = null;
        $programname= null;
        $adminfirst = null;
        $adminlast = null; 
        $mydate = date("Y-m-d");
        $studentcount = null;
        $supervisorcount = null;

        if (isset($_GET["program"]) == True && $_GET["program"] != "none") {
            $programname = $_GET["program"];

            $result1 = mysqli_query($con,"SELECT * FROM program WHERE program_name = '$programname'");
            while ($row = mysqli_fetch_array($result1)){
                $programID = $row["program_ID"];
            }

            $adminID = $_SESSION["id"];

            $result2 = mysqli_query($con,"SELECT * FROM admin WHERE admin_ID = '$adminID'");
            while ($row = mysqli_fetch_array($result2)){
                $adminfirst = $row["admin_firstname"];
                $adminlast = $row["admin_lastname"];
            }

            $result3 = mysqli_query($con, "SELECT program.program_ID, student.program_ID FROM program
            JOIN student ON program.program_ID = student.program_ID WHERE program.program_ID ='$programID'");
            $studentcount = mysqli_num_rows($result3);

            $result4 = mysqli_query($con, "SELECT program.program_ID, supervisor.program_ID FROM program
            JOIN supervisor ON program.program_ID = supervisor.program_ID WHERE program.program_ID ='$programID'");
            $supervisorcount = mysqli_num_rows($result4);

        }
        else{
            $programname = null;
            $programID = null;
        }


     ?>

    <div id="myreportbg">
        <img src="http://localhost/admin/image/Logo2.png" id="logo">
        <span id="subreport">Grading Report</span>
    
    <?php 

    if ($programname == null){
        echo'
        <div id="innerreport">
            <span id="repdetail">Report Details:</span><br><br>
            <span id="progid" class="detail">Program ID: AutoGenerated</span><br><br>
            <span id="progname" class="detail">Program Name: AutoGenerate</span><br><br>
            <span id="generatename" class="detail">Generated By: AutoGenerated</span><br><br>
            <span id="generatedate" class="detail">Generated Date: Autogenerated</span><br><br>
            <span id="student" class="detail">Total Student: AutoGenerated</span><br><br>
            <span id="supervisor" class="detail">Total Supervisor: AutoGenerated</span>
        </div>
    

        <hr id="reportline">

        <div id="contentreport">
            <span class="title0">Student ID</span>
            <span class="title1">Student Name</span>
            <span class="title2">Marks </span>
            <span class="title3">Grade </span>
        </div>
        
        <div class="reportbg2">
            <div id="mydata">
                <span id="titlea"> </span>
                <span id="titleb"> </span>
                <span id="titlec"> </span>
                <span id="titled"> </span>
            </div>
        </div>';
    }
    else{
        echo'
        <div id="innerreport">
            <span id="repdetail">Report Details:</span><br><br>
            <span id="progid" class="detail">Program ID: '.$programID.'</span><br><br>
            <span id="progname" class="detail">Program Name: '.$programname.'</span><br><br>
            <span id="generatename" class="detail">Generated By: '.$adminfirst.' '.$adminlast.'</span><br><br>
            <span id="generatedate" class="detail">Generated Date: '.$mydate.'</span><br><br>
            <span id="student" class="detail">Total Student: '.$studentcount.'</span><br><br>
            <span id="supervisor" class="detail">Total Supervisor: '.$supervisorcount.'</span>
        </div>
    

        <hr id="reportline">';

        echo'
        <div id="contentreport">
            <span class="title0">Student ID</span>
            <span class="title1">Student Name</span>
            <span class="title2"> Marks </span>
            <span class="title3"> Grade </span>
        </div>

        <div class="reportbg2">';
        
        $result5 = mysqli_query($con,"SELECT student.student_ID, student.student_firstname,
        student.student_lastname, project.project_grade FROM student 
        JOIN project ON student.project_ID = project.project_ID
        WHERE student.program_ID = '$programID'");

        while ($row = mysqli_fetch_array($result5)){

        echo'
            <div id="mydata">
                <span id="titlea">'.$row["student_ID"].' </span>
                <span id="titleb">'.$row["student_firstname"].' '.$row["student_lastname"].' </span>
                <span id="titlec">'.$row["project_grade"].'</span>';

        if ($row["project_grade"] >= 80){
            echo '<span id="titled"> A+ </span>';
        }else if ($row["project_grade"] >= 75 && $row["project_grade"] <= 79){
            echo '<span id="titled"> A </span>';
        }else if ($row["project_grade"] >= 70 && $row["project_grade"] <= 74){
            echo '<span id="titled"> B+ </span>';
        }else if ($row["project_grade"] >= 65 && $row["project_grade"] <= 69){
            echo '<span id="titled"> B </span>';
        }else if ($row["project_grade"] >= 60 && $row["project_grade"] <= 64){
            echo '<span id="titled"> C+ </span>';
        }else if ($row["project_grade"] >= 55 && $row["project_grade"] <= 59){
            echo '<span id="titled"> C </span>';
        }else if ($row["project_grade"] >= 50 && $row["project_grade"] <= 54){
            echo '<span id="titled"> C- </span>';
        }else if ($row["project_grade"] >= 40 && $row["project_grade"] <= 49){
            echo '<span id="titled"> D </span>';
        }else if ($row["project_grade"] >= 30 && $row["project_grade"] <= 39){
            echo '<span id="titled"> F+ </span>';
        }else if ($row["project_grade"] >= 20 && $row["project_grade"] <= 29){
            echo '<span id="titled"> F </span>';
        }else if ($row["project_grade"] >= 0 && $row["project_grade"] <= 19){
            echo '<span id="titled"> F- </span>';
        }

        echo '</div>';
        }

        echo 
        '</div>';
    }
    ?>

    
    <div class="graderangebg">
        <span id="grade"> Grades: </span>
        <span class="grade" id="grade1"> 80-100 A+ </span> <br><br>
        <span class="grade" id="grade2"> 75-79 A </span> <br><br>
        <span class="grade" id="grade3"> 70-74 B+ </span> <br><br>
        <span class="grade" id="grade4"> 65-69 B </span> <br><br>
        <span class="grade" id="grade5"> 60-64 C+ </span> <br><br>
        <span class="grade" id="grade6"> 55-59 C </span> <br><br>
        <span class="grade" id="grade7"> 50-54 C- </span> <br><br>
        <span class="grade" id="grade8"> 40-49 D </span> <br><br>
        <span class="grade" id="grade9"> 30-39 F+ </span><br><br>
        <span class="grade" id="grade10"> 20-29 F </span><br><br>
        <span class="grade" id="grade11"> 0-19 F- </span>
    </div>

        <div id="copyright"> <i class='bx bx-copyright'></i> Copyrighted By ProjectPlannerX 2023</div>
    </div>

    <hr class="divider">


</body>
</html>