<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Submission Report</title>
    <link rel="stylesheet" href="submission_report.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>
    <a href="admin_report.php" ><div id="goback"><i class='bx bx-chevrons-left' id="icon"></i>Back</div></a>
    <span id="progtitle">Please Provide a Program Name: </span>

    <form action="submission_report.php" method="GET">
        <select required id="programselection" name="program">
            <option value="none">none</option>
            <?php
                include("conn.php");
                include("session.php");

                $result = mysqli_query($con, "SELECT * FROM program");
                while ($row = mysqli_fetch_array($result)){
                    echo '<option value="'.$row["program_name"].'">'.$row["program_name"].'</option>';
                }

            ?>
        </select>
        <button type="submit" class="submitbutton">Submit</button>
    </form>


    <div id="print" onclick="window.print()"><i class='bx bx-printer'></i></div>

    <?php
        $programID = null;
        $programname= null;
        $adminfirst = null;
        $adminlast = null; 
        $mydate = date("Y-m-d");
        $studentcount = null;
        $supervisorcount = null;

        if (isset($_GET["program"]) == True && $_GET["program"] != "none") {
            $programname = $_GET["program"];

            $result1 = mysqli_query($con,"SELECT * FROM program WHERE program_name = '$programname'");
            while ($row = mysqli_fetch_array($result1)){
                $programID = $row["program_ID"];
            }

            $adminID = $_SESSION["id"];

            $result2 = mysqli_query($con,"SELECT * FROM admin WHERE admin_ID = '$adminID'");
            while ($row = mysqli_fetch_array($result2)){
                $adminfirst = $row["admin_firstname"];
                $adminlast = $row["admin_lastname"];
            }

            $result3 = mysqli_query($con, "SELECT program.program_ID, student.program_ID FROM program
            JOIN student ON program.program_ID = student.program_ID WHERE program.program_ID ='$programID'");
            $studentcount = mysqli_num_rows($result3);

            $result4 = mysqli_query($con, "SELECT program.program_ID, supervisor.program_ID FROM program
            JOIN supervisor ON program.program_ID = supervisor.program_ID WHERE program.program_ID ='$programID'");
            $supervisorcount = mysqli_num_rows($result4);

        }
        else{
            $programname = null;
            $programID = null;
        }


     ?>

    <div id="myreportbg">
        <img src="http://localhost/admin/image/Logo2.png" id="logo">
        <span id="subreport">Submission Report</span>
    
    <?php 

    if ($programname == null){
        echo'
        <div id="innerreport">
            <span id="repdetail">Report Details:</span><br><br>
            <span id="progid" class="detail">Program ID: AutoGenerated</span><br><br>
            <span id="progname" class="detail">Program Name: AutoGenerate</span><br><br>
            <span id="generatename" class="detail">Generated By: AutoGenerated</span><br><br>
            <span id="generatedate" class="detail">Generated Date: Autogenerated</span><br><br>
            <span id="student" class="detail">Total Student: AutoGenerated</span><br><br>
            <span id="supervisor" class="detail">Total Supervisor: AutoGenerated</span>
        </div>
    

        <hr id="reportline">

        <div id="contentreport">
            <span class="title0">Student ID</span>
            <span class="title1">Student Name</span>
            <span class="title2">Proposal </span>
            <span class="title3">Project </span>
        </div>
        
        <div class="reportbg2">
            <div id="mydata">
                <span id="titlea"> </span>
                <span id="titleb"> </span>
                <span id="titlec"> </span>
                <span id="titled"> </span>
            </div>
        </div>';
    }
    else{
        echo'
        <div id="innerreport">
            <span id="repdetail">Report Details:</span><br><br>
            <span id="progid" class="detail">Program ID: '.$programID.'</span><br><br>
            <span id="progname" class="detail">Program Name: '.$programname.'</span><br><br>
            <span id="generatename" class="detail">Generated By: '.$adminfirst.' '.$adminlast.'</span><br><br>
            <span id="generatedate" class="detail">Generated Date: '.$mydate.'</span><br><br>
            <span id="student" class="detail">Total Student: '.$studentcount.'</span><br><br>
            <span id="supervisor" class="detail">Total Supervisor: '.$supervisorcount.'</span>
        </div>
    

        <hr id="reportline">';

        echo'
        <div id="contentreport">
            <span class="title0">Student ID</span>
            <span class="title1">Student Name</span>
            <span class="title2">Proposal </span>
            <span class="title3">Project </span>
        </div>

        <div class="reportbg2">';
        
        $result5 = mysqli_query($con,"SELECT student.student_ID, student.student_firstname,
        student.student_lastname, proposal.proposal_ID, project.project_ID
        FROM student 
        JOIN project ON student.project_ID = project.project_ID
        JOIN proposal ON proposal.proposal_ID = project.proposal_ID
        WHERE student.program_ID = '$programID'");

        while ($row = mysqli_fetch_array($result5)){

        echo'
            <div id="mydata">
                <span id="titlea">'.$row["student_ID"].' </span>
                <span id="titleb">'.$row["student_firstname"].' '.$row["student_lastname"].' </span>';


            if (!$row["proposal_ID"] || $row["proposal_ID"] == "null" || $row["proposal_ID"] == "") {
                echo "<span id='titlec2'>Not Submitted</span>";
            } else {
                echo "<span id='titlec'>Submitted</span>";
            }

            if (!$row["project_ID"] ||$row["project_ID"]== "null" || $row["project_ID"]== ""){
                echo "<span id='titled2'>Not Submitted </span>";
            } else{
                echo "<span id='titled'>Submitted </span>";           
            }

        echo '</div>';
        }

        echo 
        '</div>';
    }
    ?>

        <div id="copyright"> <i class='bx bx-copyright'></i> Copyrighted By ProjectPlannerX 2023</div>
    </div>

    <hr class="divider">


</body>
</html>